### ISSUE TITLE
Won't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by davidaknowles** [conda-forge/r-intervals-feedstock#1]
Running
`conda install -c conda-forge r-intervals`
I get an error that r-intervals can't be found. 

**conda info:**
              platform : linux-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : 3.0.9
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /scr/miniconda2  (writable)
    default environment : /scr/miniconda2
       envs directories : /scr/miniconda2/envs
                          /afs/cs.stanford.edu/u/davidknowles/.conda/envs
          package cache : /scr/miniconda2/pkgs
                          /afs/cs.stanford.edu/u/davidknowles/.conda/pkgs
           channel URLs : https://conda.anaconda.org/davidaknowles/linux-64
                          https://conda.anaconda.org/davidaknowles/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/bcbio/linux-64
                          https://conda.anaconda.org/bcbio/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /afs/cs.stanford.edu/u/davidknowles/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.14.2 CPython/2.7.13 Linux/3.13.0-92-generic debian/jessie/sid glibc/2.19    
                UID:GID : 14439:100

**conda list** output is attached. 
[conda_list_urls.txt](https://github.com/conda-forge/r-intervals-feedstock/files/1198780/conda_list_urls.txt)

**Comment by ocefpaf** [comment]
I can see the files in the channel [here](https://anaconda.org/conda-forge/r-intervals/files). That sounds like an intermittent network issue. Can you try it again?

**Comment by davidaknowles** [comment]
Hmm... I think I was having issues because of having some R stuff from bioconda and some from conda-forge. A clean conda install with just conda-forge seems fine. Apologies!
